// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef ImcProgramUi_h
#define ImcProgramUi_h
#include <FL/Fl.H>
#include <FL/fl_ask.H>
/**
   added in header only, because of redefiniion issues
*/
enum menunames {MANAGE, SAVE, QUIT, HELP}; 
/**
   added in header only, because of redefiniion issues
*/
enum databasecontrols {OPEN_TABLE, CREATE_TABLE, DELETE_TABLE, SAVE_DATA, DELETE_DATA, OK1, OK2}; 
#include <FL/Fl_Double_Window.H>
extern void WinQuit_cb(Fl_Double_Window*, void*);
#include <FL/Fl_Input.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Return_Button.H>
extern void Button_cb(Fl_Return_Button*, void*);
#include <FL/Fl_Menu_Bar.H>
extern void Menu_cb(Fl_Menu_*, menunames);

class MainWindow {
public:
  /**
     Declaring text buffer in global scope, 
     static in source file only, dont know why, 
     but just work like this.
  */
  Fl_Text_Buffer *buff; 
  void hide();
  void show();
  Fl_Double_Window* make();
  Fl_Double_Window *mainwindow;
  Fl_Input *Name;
  Fl_Value_Input *Weight;
  Fl_Value_Input *Height;
  Fl_Text_Display *Display;
  Fl_Return_Button *Enter;
  static Fl_Menu_Item menu_[];
};
#include <FL/Fl_Button.H>
extern void Buttons_cb(Fl_Button*, databasecontrols);
extern void Ok_cb(Fl_Return_Button*, databasecontrols);

class WindowTables {
public:
  Fl_Text_Buffer *buff; 
  void hide();
  void show();
  void label(const char* label);
  Fl_Double_Window* make();
  Fl_Double_Window *tableswindow;
  Fl_Button *CreateTable;
  Fl_Button *DeleteTable;
  Fl_Button *OpenTable;
  Fl_Return_Button *Ok;
  Fl_Value_Input *Number;
  Fl_Input *Text;
  Fl_Text_Display *Display;
};

class WindowData {
public:
  Fl_Text_Buffer *buff; 
  void hide();
  void show();
  void label(const char* label);
  Fl_Double_Window* make();
  Fl_Double_Window *datawindow;
  Fl_Button *SaveData;
  Fl_Button *DeleteData;
  Fl_Return_Button *Ok;
  Fl_Value_Input *Number;
  Fl_Text_Display *Display;
};
#endif
